version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.springframework.boot:spring-boot-dependencies
    versions:
    - 2.4.2
    - 2.4.3
    - 2.4.4
  - dependency-name: io.micrometer:micrometer-core
    versions:
    - 1.6.3
    - 1.6.4
    - 1.6.5
  - dependency-name: org.postgresql:postgresql
    versions:
    - 42.2.18
    - 42.2.19
  - dependency-name: org.springframework.security:spring-security-test
    versions:
    - 5.4.2
    - 5.4.4
    - 5.4.5
  - dependency-name: org.springframework.cloud:spring-cloud-starter-netflix-hystrix
    versions:
    - 2.2.6.RELEASE
    - 2.2.7.RELEASE
  - dependency-name: com.github.ben-manes.versions
    versions:
    - 0.36.0
